language: node_js
node_js: lts/*
arch: amd64
os: linux
dist: jammy
deploy:
  - provider: pages
    skip_cleanup: true
    keep-history: true
    local-dir: public
    github-token: $GITHUB_TOKEN
    project-name: puglisi-web
    committer-from-gh: true
    repo: JasonPuglisi/pages-jason
    target-branch: main
    fqdn: www.jasonpuglisi.com
    on:
      repo: JasonPuglisi/puglisi-web
      branch: main

before_deploy:
- git add -f public public/* public/index.html public/assets/* public/assets/stylesheets
